server:
  port: 8003 #??
spring:
  application:
    name: spring-cloud-alibaba-provider-mysql
  cloud:
    nacos:
      discovery:
        server-addr: localhost:1111
  ######################### ????? #################################
  datasource:
    username: root        #????????
    password: 123456        #???????
    url: jdbc:mysql://127.0.0.1:3306/spring_cloud_db2?useSSL=false       #???url
    driver-class-name: com.mysql.jdbc.Driver
management:
  endpoints:
    web:
      exposure:
        include: "*"   # * ?yaml ???????????????
###################################### MyBatis ?? ######################################
mybatis:
  # ?? mapper.xml ???
  mapper-locations: classpath:mybatis/mapper/*.xml
  #????????,?????????????? mapper.xml ??????????????
  type-aliases-package: net.biancheng.c.entity
  configuration:
    #???????????????????
    map-underscore-to-camel-case: true