spring:
  application:
    name: spring-cloud-alibaba-seata-storage-8006

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/seata_storage?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:1111
        namespace: public
        username:
        password:
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8719

    alibaba:
      seata:
        tx-service-group: service-storage-group

server:
  port: 8006
seata:
  application-id: ${spring.application.name}
  tx-service-group: service-storage-group

  service:
    grouplist:
      seata-server: 127.0.0.1:8091

  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:1111

  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:1111

feign:
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
###################################### MyBatis ?? ######################################
mybatis:
  # ?? mapper.xml ???
  mapper-locations: classpath:mybatis/mapper/*.xml
  #????????,?????????????? mapper.xml ??????????????
  type-aliases-package: net.biancheng.c.entity
  configuration:
    #???????????????????
    map-underscore-to-camel-case: true