server:
  port: 8803
spring:
  application:
    name: spring-cloud-alibaba-consumer-mysql-feign
  cloud:
    nacos:
      discovery:
        server-addr: localhost:1111
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719

# ?????????????????????????????? Controller ???? ?????????
service-url:
  nacos-user-service: http://spring-cloud-alibaba-provider-mysql #????????????

# ??Sentinel?Feign???
feign:
  sentinel:
    enabled: true